# Schema for the configuration files of the mailchimp_signup module.

mailchimp_signup.mailchimp_signup.*:
  type: config_entity
  label: 'Mailchimp Signup config'
  mapping:
    mcs_id:
      type: int
      label: 'ID'
    name:
      type: string
      label: 'Machine Name'
    mc_lists:
      type: blob
      label: 'Mailchimp List(s)'
    mode:
      type: int
      label: 'Mode'
    title:
      type: string
      label: 'Title'
    settings:
      type: blog
      label: 'Settings'
    status:
      type: boolean
      label: 'Status'
    
